from django.urls import path
from .views import *
urlpatterns = [
    path('<int:aspirant_id>/', aspirant_dashboard, name='aspirant_dashboard'),
    path('aspirant1_dashboard/', aspirant_dashboard1, name='aspirant_dashboard1'),
    path('grammar-checker/', grammar_checker, name='grammar_checker'),
    path('aspirant_registration/', aspirant_registration, name='aspirant_registration'),
    path('face_image/', face_image, name='face_image'),
    path('aspirant_login/', aspirant_login, name='aspirant_login'),
    path('face_identity/', face_identity, name='face_identity'),
    path('aspirant_otp/', aspirant_otp, name='aspirant_otp'),
    path('aspirant_password_reset/', aspirant_password_reset, name='aspirant_password_reset'),
    path('aspirant_logout/', aspirant_logout, name='aspirant_logout'),

    # main pages
    path('l_correct_summary_test/', l_correct_summary_test, name='l_correct_summary_test'),
    path('l_fill_blanks_test/', l_fill_blanks_test, name='l_fill_blanks_test'),
    path('l_mcq_single_test/', l_mcq_single_test, name='l_mcq_single_test'),
    path('r_mcq_multiple_test/', r_mcq_multiple_test, name='r_mcq_multiple_test'),
    path('r_mcq_single_test/', r_mcq_single_test, name='r_mcq_single_test'),
    path('submit-mcq-single/', submit_mcq_single, name='submit_mcq_single'),
    path('s_read_aloud_test/', s_read_aloud_test, name='s_read_aloud_test'),
    path('s_short_answer_test/', s_short_answer_test, name='s_short_answer_test'),
    path('w_summarize_passage_test/', w_summarize_passage_test, name='w_summarize_passage_test'),
    path('aspirant_test/', aspirant_test, name='aspirant_test'),
    path('aspirant_result/', aspirant_result, name='aspirant_result'),
    path('submit-text/', submit_text, name='submit_text'),
    path('short_answer_submit/', short_answer_submit, name='short_answer_submit'),
    path('summarize_submit', summarize_submit, name='summarize_submit'),
    path('submit_mcq', submit_mcq, name='submit_mcq'),
    path('mcq_l_submit', mcq_l_submit, name="mcq_l_submit",),
    path('l_mcq_single_submit', l_mcq_single_test_submit, name='l_mcq_single_submit'),
    path('fill_in_blank_submit', fill_in_blank_submit, name='fill_in_blank_submit'),
    #test
    # path('sequential_test/', sequential_test, name='sequential_test'),
#     path('sequential_test_submit/', sequential_test_submit, name='sequential_test_submit'),
#     path('sequential_test_start/', sequential_test_start, name='sequential_test_start'),
#     path('sequential_test_next/', sequential_test_next, name='sequential_test_next'),
#     path('sequential_s_read_aloud_test/', sequential_s_read_aloud_test, name='sequential_s_read_aloud_test'),
#     path('sequential_r_mcq_single_test/', sequential_r_mcq_single_test, name='sequential_r_mcq_single_test'),
#     path('sequential_w_summarize_passage_test/', sequential_w_summarize_passage_test, name='sequential_w_summarize_passage_test'),
#     path('sequential_l_mcq_single_test/', sequential_l_mcq_single_test, name='sequential_l_mcq_single_test'),
#     path('sequential_s_short_answer_test/', sequential_s_short_answer_test, name='sequential_s_short_answer_test'),
#     path('sequential_l_correct_summary_test/', sequential_l_correct_summary_test, name='sequential_l_correct_summary_test'),
#     path('sequential_l_fill_blanks_test/', sequential_l_fill_blanks_test, name='sequential_l_fill_blanks_test'),
#     path('sequential_r_mcq_multiple_test/', sequential_r_mcq_multiple_test, name='sequential_r_mcq_multiple_test'),
 ]
