# Generated by Django 5.1.5 on 2025-02-04 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_readmcqsingle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadMCQSingle',
        ),
    ]
