# Generated by Django 5.1.5 on 2025-02-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_readmcqmultiple'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadMCQMultiple',
        ),
    ]
