# Generated by Django 5.1.5 on 2025-02-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_readmcqmultiple'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadMCQMultiple',
        ),
    ]
