# Generated by Django 5.1.5 on 2025-02-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_listeningmcqsingle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListeningMCQSingle',
        ),
    ]
