# Generated by Django 5.1.5 on 2025-02-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_listeningmcqsingle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadMCQMultiple',
        ),
        migrations.DeleteModel(
            name='ReadMCQSingle',
        ),
    ]
