# Generated by Django 5.1.5 on 2025-02-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_listeningcorrectsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningFillBlanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audios2/')),
                ('passage', models.TextField()),
                ('answers', models.JSONField()),
            ],
        ),
    ]
