# Generated by Django 5.1.6 on 2025-02-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_listeningfillblanks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListeningCorrectSummary',
        ),
        migrations.DeleteModel(
            name='ListeningFillBlanks',
        ),
        migrations.DeleteModel(
            name='ListeningMCQSingle',
        ),
        migrations.DeleteModel(
            name='ShortAnswer',
        ),
    ]
