# Generated by Django 5.1.6 on 2025-02-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0019_listeningcorrectsummary_listeningfillblanks_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListeningCorrectSummary',
        ),
        migrations.DeleteModel(
            name='ListeningFillBlanks',
        ),
        migrations.DeleteModel(
            name='ListeningMCQSingle',
        ),
        migrations.DeleteModel(
            name='ShortAnswer',
        ),
    ]
