# Generated by Django 5.1.7 on 2025-03-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0022_resulthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultHistory',
        ),
    ]
