# Generated by Django 5.1.6 on 2025-02-08 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0021_listeningcorrectsummary_listeningfillblanks_and_more'),
        ('aspirant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=255)),
                ('reg_id', models.IntegerField()),
                ('mark', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingMCQSingleTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=255)),
                ('reg_id', models.IntegerField()),
                ('answer', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.readmcqsingle')),
            ],
        ),
    ]
