# Generated by Django 5.1.6 on 2025-02-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspirant', '0002_testresult_readingmcqsingletest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
