# Generated by Django 5.1.6 on 2025-02-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirant', '0003_delete_testresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=255)),
                ('reg_id', models.IntegerField()),
                ('mark', models.IntegerField(default=0)),
            ],
        ),
    ]
