# Generated by Django 5.1.6 on 2025-02-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspirant', '0004_readingtestresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingmcqsingletest',
            name='question',
        ),
        migrations.DeleteModel(
            name='ReadingTestResult',
        ),
        migrations.DeleteModel(
            name='ReadingMCQSingleTest',
        ),
    ]
