# Generated by Django 5.1.6 on 2025-02-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspirant', '0008_readingmcqsingletest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadingMCQSingleTest',
        ),
    ]
