# Generated by Django 5.1.6 on 2025-03-09 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirant', '0018_listeningfillblankssubmit'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingtestresult',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
