# Generated by Django 5.1.7 on 2025-03-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspirant', '0021_resulthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resulthistory',
            name='total',
        ),
    ]
